removed LastName, fix for issue #20
pkp/shibboleth pull request #22
Opened 2023-01-25 12:51 UTC by Lenare326

Quick fix for issue #20 that simply removes the assignment of the LastName attribute.
Tested on OJS 3.3.0.-13

2023-01-25 14:34 UTC, ctgraham requested changes
There are some unrelated changes pulled in from commit 345833a, and we will want to make the family name optional rather than remove it entirely.

2023-01-25 14:34 UTC, ctgraham commented on pages/ShibbolethHandler.inc.php
> +		if (empty($uin) || empty($userEmail) || empty($userFirstName)) {
Can you alter this PR to make the familyName optional, rather than removed entirely?

2023-01-25 14:34 UTC, ctgraham commented on pages/ShibbolethHandler.inc.php
> +
There are some inadvertent changes included in this PR unrelated to the bugfix.

2023-01-25 14:35 UTC, ctgraham commented
Thanks, @Lenare326 !  I have some changes requested before we can merge and release this fix.

2023-01-26 07:23 UTC, Lenare326 commented
Thanks for the hint, @ctgraham! I've made the changes you requested.

2023-01-26 15:33 UTC, ctgraham approved these changes

2023-03-09 18:52 UTC, merged